# CONFIGURAÇÕES GERAIS DO SIMULADOR

# MODO DE EXECUÇÃO: "desenvolvimento", "teste","producao".
MODO = "desenvolvimento"

NOME_EMPRESA = "Amplo Varejo S.A" 

# HORIZONTE DE SIMULAÇÃO
ANO_INICIO = "2025-01-01"
ANO_FIM = "2025-12-31"

# QUANTIDADES
if MODO == "desenvolvimento":
    QUANTIDADE_REGIOES = 5
    QUANTIDADE_LOJAS = 50
    QUANTIDADE_CATEGORIAS = 4
    QUANTIDADE_CLIENTES = 7500
    QUANTIDADE_VENDEDORES = 100

    PEDIDOS_MINIMOS_DIA = 20
    PEDIDOS_MAXIMOS_DIA = 35

elif MODO == "teste":
    QUANTIDADE_REGIOES = 5
    QUANTIDADE_LOJAS = 100
    QUANTIDADE_CATEGORIAS = 4
    QUANTIDADE_CLIENTES = 10000
    QUANTIDADE_VENDEDORES = 200

    PEDIDOS_MINIMOS_DIA = 200
    PEDIDOS_MAXIMOS_DIA = 500

elif MODO == "producao":
    QUANTIDADE_REGIOES = 5
    QUANTIDADE_LOJAS = 340
    QUANTIDADE_CATEGORIAS = 4
    QUANTIDADE_CLIENTES = 100000
    QUANTIDADE_VENDEDORES = 1200

    PEDIDOS_MINIMOS_DIA = 1500
    PEDIDOS_MAXIMOS_DIA = 3500

else:
    raise ValueError("Modo de execução inválido!")

# ESTOQUE
ESTOQUE_MINIMO = 20
ESTOQUE_MAXIMO = 500

# ITENS
ITENS_MINIMOS_PEDIDO = 1
ITENS_MAXIMOS_PEDIDO = 3

QUANTIDADE_MINIMA_ITEM = 1
QUANTIDADE_MAXIMA_ITEM = 2

# ALEATORIEDADE
SEMENTE_ALEATORIA = 42

