-- MySQL Script generated by MySQL Workbench
-- Mon Aug 10 17:12:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema amplo_varejo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amplo_varejo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amplo_varejo` DEFAULT CHARACTER SET utf8 ;
USE `amplo_varejo` ;

-- -----------------------------------------------------
-- Table `amplo_varejo`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`estados` (
  `id_estado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_estado` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `regiao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `nome_estado_UNIQUE` (`nome_estado` ASC) VISIBLE,
  UNIQUE INDEX `uf_UNIQUE` (`uf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`lojas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`lojas` (
  `id_loja` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_loja` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `id_estado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_loja`),
  UNIQUE INDEX `nome_loja_UNIQUE` (`nome_loja` ASC) VISIBLE,
  INDEX `fk_lojas_estados_idx` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_lojas_estados`
    FOREIGN KEY (`id_estado`)
    REFERENCES `amplo_varejo`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`categorias` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nome_categoria_UNIQUE` (`nome_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`calendario` (
  `id_calendario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `ano` INT UNSIGNED NOT NULL,
  `mes` INT UNSIGNED NOT NULL,
  `nome_mes` VARCHAR(45) NOT NULL,
  `trimestre` TINYINT NOT NULL,
  `semestre` TINYINT NOT NULL,
  `dia` TINYINT NOT NULL,
  `dia_semana` VARCHAR(45) NOT NULL,
  `dia_util` TINYINT NOT NULL,
  `final_de_semana` TINYINT NOT NULL,
  PRIMARY KEY (`id_calendario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`clientes` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf_cliente` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `id_loja` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_clientes_lojas1_idx` (`id_loja` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_lojas1`
    FOREIGN KEY (`id_loja`)
    REFERENCES `amplo_varejo`.`lojas` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`vendedores` (
  `id_vendedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_vendedor` VARCHAR(45) NOT NULL,
  `cpf_vendedor` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `id_loja` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  UNIQUE INDEX `nome_vendedor_UNIQUE` (`nome_vendedor` ASC) VISIBLE,
  UNIQUE INDEX `cpf_vendedor_UNIQUE` (`cpf_vendedor` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_vendedores_lojas1_idx` (`id_loja` ASC) VISIBLE,
  CONSTRAINT `fk_vendedores_lojas1`
    FOREIGN KEY (`id_loja`)
    REFERENCES `amplo_varejo`.`lojas` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`pedidos` (
  `id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_calendario` INT UNSIGNED NOT NULL,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_vendedor` INT UNSIGNED NOT NULL,
  `id_loja` INT UNSIGNED NOT NULL,
  `status` ENUM("pendente", "pago", "cancelado", "enviado") NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedidos_calendario1_idx` (`id_calendario` ASC) VISIBLE,
  INDEX `fk_pedidos_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_pedidos_vendedores1_idx` (`id_vendedor` ASC) VISIBLE,
  INDEX `fk_pedidos_lojas1_idx` (`id_loja` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_calendario1`
    FOREIGN KEY (`id_calendario`)
    REFERENCES `amplo_varejo`.`calendario` (`id_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `amplo_varejo`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_vendedores1`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `amplo_varejo`.`vendedores` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_lojas1`
    FOREIGN KEY (`id_loja`)
    REFERENCES `amplo_varejo`.`lojas` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`produtos` (
  `id_produto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(10,2) UNSIGNED NOT NULL,
  `custo` DECIMAL(10,2) UNSIGNED NOT NULL,
  `ativo` TINYINT NOT NULL,
  `id_categoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `nome_produto_UNIQUE` (`nome_produto` ASC) VISIBLE,
  INDEX `fk_produtos_categorias1_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `amplo_varejo`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`itens_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`itens_pedido` (
  `id_item_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pedido` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `valor_unitario` DECIMAL(10,2) UNSIGNED NOT NULL,
  `desconto` DECIMAL(10,2) UNSIGNED NOT NULL,
  `sub_total` DECIMAL(10,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_item_pedido`),
  INDEX `fk_itens_pedido_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_itens_pedido_produtos1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_itens_pedido_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `amplo_varejo`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_pedido_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `amplo_varejo`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`estoque` (
  `id_estoque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_loja` INT UNSIGNED NOT NULL,
  `id_produto` INT UNSIGNED NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_estoque`),
  INDEX `fk_estoque_lojas1_idx` (`id_loja` ASC) VISIBLE,
  INDEX `fk_estoque_produtos1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_lojas1`
    FOREIGN KEY (`id_loja`)
    REFERENCES `amplo_varejo`.`lojas` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `amplo_varejo`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`movimentacao_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`movimentacao_estoque` (
  `id_movimentacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_estoque` INT UNSIGNED NOT NULL,
  `id_item_pedido` INT UNSIGNED NOT NULL,
  `tipo_movimentacao` ENUM("Saída", "Entrada") NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  `id_calendario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_movimentacao`),
  INDEX `fk_movimentacao_estoque_estoque1_idx` (`id_estoque` ASC) VISIBLE,
  INDEX `fk_movimentacao_estoque_itens_pedido1_idx` (`id_item_pedido` ASC) VISIBLE,
  INDEX `fk_movimentacao_estoque_calendario1_idx` (`id_calendario` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacao_estoque_estoque1`
    FOREIGN KEY (`id_estoque`)
    REFERENCES `amplo_varejo`.`estoque` (`id_estoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_estoque_itens_pedido1`
    FOREIGN KEY (`id_item_pedido`)
    REFERENCES `amplo_varejo`.`itens_pedido` (`id_item_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_estoque_calendario1`
    FOREIGN KEY (`id_calendario`)
    REFERENCES `amplo_varejo`.`calendario` (`id_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`metas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`metas` (
  `id_meta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mes` INT NOT NULL,
  `id_loja` INT UNSIGNED NOT NULL,
  `meta_faturamento` INT NOT NULL,
  `meta_pedidos` INT NOT NULL,
  `meta_ticket_medio` INT NOT NULL,
  PRIMARY KEY (`id_meta`),
  INDEX `fk_metas_lojas1_idx` (`id_loja` ASC) VISIBLE,
  CONSTRAINT `fk_metas_lojas1`
    FOREIGN KEY (`id_loja`)
    REFERENCES `amplo_varejo`.`lojas` (`id_loja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`campanhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`campanhas` (
  `id_campanha` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `mes_inicio` INT UNSIGNED NOT NULL,
  `dia_inicio` INT UNSIGNED NOT NULL,
  `mes_fim` INT UNSIGNED NOT NULL,
  `dia_fim` INT UNSIGNED NOT NULL,
  `desconto_percentual` INT UNSIGNED NOT NULL,
  `multiplicador_vendas` DOUBLE NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `prioridade` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_campanha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`eventos` (
  `id_evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_evento` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `regiao` VARCHAR(45) NOT NULL,
  `probabilidade` DOUBLE NOT NULL,
  `impacto_vendas` DOUBLE NOT NULL,
  `duracao_dias` INT NOT NULL,
  `prioridade` INT NOT NULL,
  `ativo` TINYINT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_evento`),
  UNIQUE INDEX `nome_evento_UNIQUE` (`nome_evento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amplo_varejo`.`sazonalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amplo_varejo`.`sazonalidade` (
  `mes` INT UNSIGNED NOT NULL,
  `nome_mes` VARCHAR(45) NOT NULL,
  `indice_vendas` DOUBLE NOT NULL,
  `classificacao` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  UNIQUE INDEX `mes_UNIQUE` (`mes` ASC) VISIBLE,
  UNIQUE INDEX `nome_mes_UNIQUE` (`nome_mes` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
